language: r
cache: packages
dist: xenial

# ----------------+-------------+---------+--------------+-------------+
# Environment     | R CMD CHECK | codecov | goodpractice | rough tests |
# ----------------+-------------+---------+--------------+-------------+
# MacOS           | Yes         | Yes     | No           | No          |
# Linux r-devel   | Yes         | No      | Yes          | No          |
# Linux r-release | No          | No      | No           | Yes         |
# ----------------+-------------+---------+--------------+-------------+
matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx


r_github_packages:
  - Giappo/mbd
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/beastier@develop
  - ropensci/mauricer
  - ropensci/babette
  - ropensci/tracerer@develop
  - richelbilderbeek/mcbette
  - richelbilderbeek/nLTT
  - rsetienne/PBD/PBD
  - richelbilderbeek/becosys

before_install:
  - echo $TRAVIS_R_VERSION_STRING
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi

before_script:
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e "mauricer::install_beast2_pkg(\"NS\")"
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi

script:
  - travis_wait 60 R CMD build .
  # Check on Mac and r-devel
  - if [ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_R_VERSION_STRING" == "devel" ]; then travis_wait 60 R CMD check *tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" != "linux" ]; then travis_wait 60 R CMD check *tar.gz; fi

after_success:
  # Mac only
  - if [ "$TRAVIS_OS_NAME" != "linux" ]; then Rscript -e 'travis_wait 20 Rscript -e 'covr::codecov()'; fi
  # r-devel
  - if [ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_R_VERSION_STRING" == "devel" ]; then Rscript -e 'lintr::lint_package()'; fi

after_failure:
  - cat /home/travis/build/richelbilderbeek/pirouette/pirouette.Rcheck/00check.log
  - cd ~; find . | egrep "beast"
  - cd ~; find . | egrep "\.log"
  - cd ~; find . | egrep "\.trees"
  - cd ~; find . | egrep "\.xml"
  - cd ~; find . | egrep "\.xml\.state"
  - cd ~; find . | egrep "\.fasta"
