language: r
cache: packages


# ----------------+-------------+---------+-------+--------------+-------------+
# Environment     | R CMD CHECK | codecov | lintr | goodpractice | rough tests |
# ----------------+-------------+---------+-------+--------------+-------------+
# MacOS           | No          | No      | No    | No (*)       | No          |
# Linux r-devel   | No          | Yes     | No    | No           | Yes         |
# Linux r-release | Yes         | No      | Yes   | No           | No          |
# ----------------+-------------+---------+-------+--------------+-------------+
#
# (*) Would love to, but it takes >30 mins on MacOS
#

matrix:
  include:
  - r: release
    os: linux
    env: INSTALL_BEAST2=true
  - r: devel
    os: linux
    env: INSTALL_BEAST2=false
  #- r: release
  #  os: osx


r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - ropensci/mcbette
  - rsetienne/DDD
  - thijsjanzen/nodeSub

before_install:
  # Fix rJava error, from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
  - sudo $(which R) CMD javareconf
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install imagemagick@6; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi

before_script:
  - if [[ "$INSTALL_BEAST2" == true ]]; then Rscript -e "beastier::install_beast2()"; fi
  - if [[ "$INSTALL_BEAST2" == true ]]; then Rscript -e 'mauricer::install_beast2_pkg("NS")'; fi

script:
  - travis_wait 60 R CMD build .
  - if [[ "$INSTALL_BEAST2" == true ]]; then travis_wait 60 R CMD check *tar.gz; fi
  # lintr
  - if [[ "$INSTALL_BEAST2" == false ]]; then Rscript -e 'lintr::expect_lint_free()' || true; fi

after_success:
  # Codecov
  - if [[ "$INSTALL_BEAST2" == true ]]; then travis_wait 20 Rscript -e 'covr::codecov()'; fi
  # Proselint
  - if [[ "$INSTALL_BEAST2" == false ]]; then proselint *.md | egrep -v "typography\.symbols\.curly_quotes"; fi
  # Report
  - Rscript -e 'mcbette::mcbette_report()'
  # Download thesis
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf"

after_failure:
  # Report
  - Rscript -e 'mcbette::mcbette_report()'
  # Download thesis
  - wget https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf"


