language: r
cache: packages

r_packages:
  - devtools
  - ggplot2
  - TreeSim
  - xml2

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - richelbilderbeek/babette
  - richelbilderbeek/beastier
  - richelbilderbeek/beautier
  - richelbilderbeek/mauricer
  - richelbilderbeek/mcbette
  - richelbilderbeek/razzo
  - richelbilderbeek/tracerer
  - richelbilderbeek/nLTT
  - rsetienne/PBD/PBD
  - MangoTheCat/goodpractice
  - KlausVigo/phangorn

before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev

before_script:
  - sudo apt-get install -qq oracle-java8-installer # Java 8
  - sudo apt-get install oracle-java8-set-default
  - Rscript -e "beastier::install_beast2()"
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - sudo pip install proselint
  # markdown-link-check, temporarily removed due to CERT_UNTRUSTED
  #- sudo apt-get install npm
  #- sudo npm install -g markdown-link-check

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'goodpractice::gp()'
  - proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
  # temporarily removed due to CERT_UNTRUSTED
  #- ./scripts/check_dead_links

after_failure:
  # - sudo Rscript install_this_r_package.R
  # - Rscript -e 'library(beautier); testit::assert(has_beast2())'
  - cat /home/travis/build/richelbilderbeek/beautier/..Rcheck/00install.out
  - cat /home/travis/build/richelbilderbeek/beautier/..Rcheck/00check.log
  - cd ~; find . | egrep "beast"
  - cd ~; find . | egrep "\.log"
  - cd ~; find . | egrep "\.trees"
  - cd ~; find . | egrep "\.xml"
  - cd ~; find . | egrep "\.xml\.state"
  - cd ~; find . | egrep "\.fasta"
  - cat /home/travis/build/richelbilderbeek/beautier/..Rcheck/tests/testthat/testthat.log
