language: r
cache: packages
dist: xenial

r_github_packages:
  - Giappo/mbd
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/beastier@develop
  - ropensci/mauricer
  - ropensci/babette
  - ropensci/tracerer@develop
  - richelbilderbeek/mcbette
  - richelbilderbeek/nLTT
  - rsetienne/PBD/PBD
  - richelbilderbeek/becosys

before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev
  # Rmpfr
  - sudo apt install -qq libmpfr-dev

before_script:
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e "mauricer::install_beast2_pkg(\"NS\")"
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi

script:
  - travis_wait 60 R CMD build .
  - travis_wait 60 R CMD check *tar.gz

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'lintr::lint_package()'; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then Rscript -e 'travis_wait 20 Rscript -e 'covr::codecov()'; fi

after_failure:
  - cat /home/travis/build/richelbilderbeek/pirouette/pirouette.Rcheck/00check.log
  - cd ~; find . | egrep "beast"
  - cd ~; find . | egrep "\.log"
  - cd ~; find . | egrep "\.trees"
  - cd ~; find . | egrep "\.xml"
  - cd ~; find . | egrep "\.xml\.state"
  - cd ~; find . | egrep "\.fasta"
