language: r
cache: packages

r_packages:
  - devtools
  - ggplot2
  - magrittr
  - xml2

bioc_packages:
  - ggtree

# Use bioc_packages instead of GuangchuangYu/ggtree@9416b852753df0957f812840b9b5eda74b37d9b3
r_github_packages:
  - Giappo/mbd
  - jimhester/covr
  - jimhester/lintr
  - KlausVigo/phangorn
  - MangoTheCat/goodpractice
  - ropensci/beautier
  - ropensci/tracerer
  - ropensci/beastier
  - ropensci/mauricer
  - ropensci/babette@develop
  - richelbilderbeek/mcbette
  - richelbilderbeek/nLTT
  - rsetienne/PBD/PBD
  - richelbilderbeek/becosys


before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev
  # Rmpfr
  - sudo apt install -qq libmpfr-dev
  # magrittr
  - R --version
  - Rscript -e 'install.packages("magrittr", repos="http://cran.us.r-project.org")'

before_script:
  - Rscript -e "beastier::install_beast2()"
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - sudo pip install proselint

script:
  - travis_wait 50 R CMD build .
  - travis_wait 50 R CMD check *tar.gz

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  #- Rscript -e 'goodpractice::gp()'
  #- proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
  # temporarily removed due to CERT_UNTRUSTED
  #- ./scripts/check_dead_links

after_failure:
  # - sudo Rscript install_this_r_package.R
  # - Rscript -e 'library(beautier); testit::assert(has_beast2())'
  - cat /home/travis/build/ropensci/beautier/..Rcheck/00install.out
  - cat /home/travis/build/ropensci/beautier/..Rcheck/00check.log
  - cd ~; find . | egrep "beast"
  - cd ~; find . | egrep "\.log"
  - cd ~; find . | egrep "\.trees"
  - cd ~; find . | egrep "\.xml"
  - cd ~; find . | egrep "\.xml\.state"
  - cd ~; find . | egrep "\.fasta"
  - cat /home/travis/build/ropensci/beautier/..Rcheck/tests/testthat/testthat.log
