language: r
cache: packages
dist: xenial

# ----------------+-------------+---------+-------+--------------+-------------+
# Environment     | R CMD CHECK | codecov | lintr | goodpractice | rough tests |
# ----------------+-------------+---------+-------+--------------+-------------+
# MacOS           | No          | No      | No    | No (*)       | No          |
# Linux r-devel   | No          | Yes     | No    | No           | Yes         |
# Linux r-release | Yes         | No      | Yes   | No           | No          |
# ----------------+-------------+---------+-------+--------------+-------------+
#
# (*) Would love to, but it takes >30 mins on MacOS
#

matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  #- r: release
  #  os: osx


r_github_packages:
  - Giappo/mbd
  - jimhester/covr
  - jimhester/lintr
  - MangoTheCat/goodpractice
  - ropensci/beautier
  - ropensci/beastier@develop
  - ropensci/mauricer
  - ropensci/babette@develop
  - richelbilderbeek/mcbette
  - richelbilderbeek/nLTT
  - rsetienne/PBD/PBD
  - richelbilderbeek/becosys

before_install:
  - echo $TRAVIS_R_VERSION_STRING
  # ImageMagick
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:opencpu/imagemagick; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -y libmagick++-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install imagemagick@6; fi
  # Rmpfr
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt install -qq libmpfr-dev; fi
  # Java
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R CMD javareconf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then R --quiet -e 'install.packages("rJava", type="source", repos="http://cran.us.r-project.org")'; fi

before_script:
  - Rscript -e "beastier::install_beast2()"
  - Rscript -e "mauricer::install_beast2_pkg(\"NS\")"
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi

script:
  - travis_wait 60 R CMD build .
  # Check
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then travis_wait 60 R CMD check *tar.gz; fi

after_success:
  # Codecov
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "devel" ]; then travis_wait 20 Rscript -e 'covr::codecov()'; fi
  # Lint
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$TRAVIS_R_VERSION_STRING" == "release" ]; then Rscript -e 'lintr::lint_package()'; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then Rscript -e 'lintr::lint_package()'; fi
  # Goodpractice, takes >30 mins on Mac
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then Rscript -e 'goodpractice::gp()'; fi

after_failure:
  - cat /home/travis/build/richelbilderbeek/pirouette/pirouette.Rcheck/00check.log
  - cd ~; find . | egrep "beast"
  - cd ~; find . | egrep "\.log"
  - cd ~; find . | egrep "\.trees"
  - cd ~; find . | egrep "\.xml"
  - cd ~; find . | egrep "\.xml\.state"
  - cd ~; find . | egrep "\.fasta"
