language: r
cache: packages

r_packages:
  - devtools
  - ggplot2
  - xml2

r_github_packages:
  - Giappo/mbd
  - GuangchuangYu/ggtree
  - jimhester/covr
  - jimhester/lintr
  - KlausVigo/phangorn
  - MangoTheCat/goodpractice
  - ropensci/beautier
  - ropensci/tracerer
  - ropensci/beastier
  - ropensci/mauricer
  - ropensci/babette
  - richelbilderbeek/mcbette
  - richelbilderbeek/nLTT
  - rsetienne/PBD/PBD
  - richelbilderbeek/becosys

before_install:
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev
  # Rmpfr
  - sudo apt install -qq libmpfr-dev

before_script:
  - # sudo apt-get install -qq oracle-java8-installer # Java 8
  - # sudo apt-get install oracle-java8-set-default
  - Rscript -e "beastier::install_beast2()"
  - if [ -f ".lintr" ]; then echo "Do use Hadley Wickham's style guide"; exit 1; fi
  # proselint
  - sudo pip install proselint

script:
  - travis_wait 50 R CMD build .
  - travis_wait 50 R CMD check *tar.gz

after_success:
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'covr::codecov()'
  #- Rscript -e 'goodpractice::gp()'
  #- proselint *.md | egrep -v "typography\.symbols\.curly_quotes"
  # temporarily removed due to CERT_UNTRUSTED
  #- ./scripts/check_dead_links

after_failure:
  # - sudo Rscript install_this_r_package.R
  # - Rscript -e 'library(beautier); testit::assert(has_beast2())'
  - cat /home/travis/build/ropensci/beautier/..Rcheck/00install.out
  - cat /home/travis/build/ropensci/beautier/..Rcheck/00check.log
  - cd ~; find . | egrep "beast"
  - cd ~; find . | egrep "\.log"
  - cd ~; find . | egrep "\.trees"
  - cd ~; find . | egrep "\.xml"
  - cd ~; find . | egrep "\.xml\.state"
  - cd ~; find . | egrep "\.fasta"
  - cat /home/travis/build/ropensci/beautier/..Rcheck/tests/testthat/testthat.log
