# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

# Inspired on https://github.com/juliasilge/tidytext
environment:
  global:
    WARNINGS_ARE_ERRORS: 0
    USE_RTOOLS: true

build_script:
  - travis-tool.sh install_r curl
  - travis-tool.sh install_github Giappo/mbd
  - travis-tool.sh install_r fansi
  - travis-tool.sh install_github thijsjanzen/nodeSub
  - travis-tool.sh install_github richelbilderbeek/beastierinstall
  - travis-tool.sh install_github richelbilderbeek/mauricerinstall
  - travis-tool.sh install_deps
  - Rscript -e "beastierinstall::install_beast2()"
  - Rscript -e 'mauricerinstall::install_beast2_package("NS")'

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip
  - Rscript -e "mcbette::mcbette_report()"

on_success:
  - Rscript -e "mcbette::mcbette_report()"

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
