---
title: "Create A Twin Tree"
author: "Richèl J.C. Bilderbeek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Create A Twin Tree}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(pirouette)
library(phangorn)
```

First create a tree, then you can twin it. Currently there are two different way to do so.
The first is generating the twin using a Birth-Death (bd) process. The second using a Yule process.

We pick this tree to twin:

```{r}
phylogeny <- ape::read.tree(text = "(((A:1, B:1):1, C:2):1, D:3);")
ape::plot.phylo(phylogeny)
```

The BD twinning parameters:

```{r}
twinning_params <- create_twinning_params()
twinning_params$twin_model <- "birth_death"
bd_twin <- create_twin_tree(
  phylogeny = phylogeny,
  twinning_params = twinning_params
)
```
The Yule twinning parameters:

```{r}
twinning_params$twin_model <- "yule"
yule_twin <- create_twin_tree(
  phylogeny = phylogeny,
  twinning_params = twinning_params
)
```

Show the true tree in red and bd twin tree in gray:

```{r fig.width=7, fig.height=7}
babette::plot_densitree(
  phylos = c(phylogeny, bd_twin), 
  col = c("red", "gray"), 
  width = 4,
  consensus = phylogeny,
  alpha = 0.5
)
```

Show the true tree in red and bd twin tree in green:

```{r fig.width=7, fig.height=7}
babette::plot_densitree(
  phylos = c(phylogeny, yule_twin), 
  col = c("red", "green"), 
  width = 4,
  consensus = phylogeny,
  alpha = 0.5
)
```
