---
title: "Interface Change Autumn 2018"
author: "Richel J.C. Bilderbeek"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{pirouette demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Load library:

```{r}
library(pirouette)
```

Create the true phylogeny:

```{r}
crown_age <- 2
true_phylogeny <- ape::read.tree(text = "((A:1,B:1):2,C:3);")
```

Define the length of the DNA sequence:

```{r}
sequence_length <- 10
mcmc <- beautier::create_mcmc(chain_length = 2000)
mutation_rate <- 0.5
```

### Old

```{r}
out <- pirouette::pir_run(
  phylogeny = true_phylogeny,
  sequence_length = sequence_length,
  mcmc = mcmc,
  mutation_rate = mutation_rate
)
```

### New

```{r}
out <- pirouette::pir_run(
  phylogeny = true_phylogeny,
  sequence_length = NULL,
  root_sequence = create_mono_nuc_dna(length = sequence_length),
  mcmc = mcmc,
  mutation_rate = mutation_rate
)
```



