test_that("use", {
  expect_silent(check_tree_and_model("true_generative"))
  expect_silent(check_tree_and_model("twin_generative"))
  expect_silent(check_tree_and_model("true_candidate"))
  expect_silent(check_tree_and_model("twin_candidate"))
  expect_error(check_tree_and_model("nonsense"))
  expect_error(check_tree_and_model(NA))
  expect_error(check_tree_and_model(NULL))
  expect_error(check_tree_and_model(Inf))
  expect_error(check_tree_and_model(c()))
  expect_error(check_tree_and_model(""))
  expect_error(check_tree_and_model(character(0)))
  expect_error(check_tree_and_model(c("twin_candidate", "twin_candidate")))
})
