test_that("use", {
  expect_silent(check_tree_and_models("true_generative"))
  expect_silent(check_tree_and_models("twin_generative"))
  expect_silent(check_tree_and_models("true_candidate"))
  expect_silent(check_tree_and_models("twin_candidate"))
  expect_silent(check_tree_and_models(c("twin_candidate", "twin_candidate")))
  expect_error(check_tree_and_models("nonsense"))
  expect_error(check_tree_and_models(NA))
  expect_error(check_tree_and_models(NULL))
  expect_error(check_tree_and_models(Inf))
  expect_error(check_tree_and_models(c()))
  expect_error(check_tree_and_models(""))
  expect_error(check_tree_and_models(character(0)))
})
