#!/bin/bash

chmod +x /home/$USER/Rlibrary/

echo "path = commandArgs(TRUE)" > Rsetup.R
echo "home_dir = substring(path,1,13)" >> Rsetup.R
echo "lib_dir = file.path(home_dir, 'Rlibrary')" >> Rsetup.R
echo ".libPaths(new = lib_dir)" >> Rsetup.R
echo "devtools::install_github('ropensci/beautier', lib = .libPaths()[1])" >> Rsetup.R
echo "devtools::install_github('ropensci/tracerer', lib = .libPaths()[1])" >> Rsetup.R
echo "devtools::install_github('ropensci/beastier', lib = .libPaths()[1])" >> Rsetup.R
echo "devtools::install_github('ropensci/mauricer', lib = .libPaths()[1])" >> Rsetup.R
echo "devtools::install_github('ropensci/babette', ref = 'develop', lib = .libPaths()[1])" >> Rsetup.R
echo "devtools::install_github('richelbilderbeek/mcbette', lib = .libPaths()[1])" >> Rsetup.R
echo "devtools::install_github('richelbilderbeek/pirouette', ref = 'giovanni', lib = .libPaths()[1])" >> Rsetup.R
echo "library(pirouette)" >> Rsetup.R

echo "#!/bin/bash" > Rsetup2
echo "#SBATCH --time=00:59:00" >> Rsetup2
echo "path='/home/$USER/pirouette'" >> Rsetup2
echo "module load R/3.5.0-foss-2018a-X11-20180131" >> Rsetup2
echo "Rscript Rsetup.R $path" >> Rsetup2
echo "rm Rsetup.R" >> Rsetup2
echo "rm Rsetup2" >> Rsetup2

chmod +x Rsetup2
./Rsetup2