#!/bin/bash
# Script to install pirouette and its dependencies
#
# Usage, locally:
#
#   ./install_pir_deps
#
Rscript -e 'remotes::install_github("richelbilderbeek/nLTT")'
Rscript -e 'remotes::install_github("ropensci/beautier")'
Rscript -e 'remotes::install_github("ropensci/tracerer")'
Rscript -e 'remotes::install_github("ropensci/beastier")'
Rscript -e 'remotes::install_github("ropensci/mauricer")'
Rscript -e 'remotes::install_github("ropensci/babette")'
Rscript -e 'remotes::install_github("richelbilderbeek/mcbette")'
Rscript -e 'if (!beastier::is_beast2_installed()) beastier::install_beast2()'
Rscript -e 'if (!mauricer::is_beast2_ns_pkg_installed()) mauricer::install_beast2_pkg("NS")'
