# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
  pull_request:

name: R-CMD-check

jobs:
  R-CMD-check:
    strategy:
      matrix:
        include:
          - install_beast2_ns: "true" 
          - install_beast2_ns: "false"

    runs-on: ubuntu-18.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install libgit2-dev
        run: sudo apt install -qq libgit2-dev

      - name: Install libmpfr-dev for Rmpfr
        run: sudo apt install -qq libmpfr-dev

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      # from https://travis-ci.community/t/cannot-connect-to-java-from-r/9754/8
      - name: Fix rJava error
        run: sudo $(which R) CMD javareconf

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rJava")
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
          remotes::install_cran("lintr")
          remotes::install_github("MangoTheCat/goodpractice")
          remotes::install_github("richelbilderbeek/beautier", ref = "develop")
          remotes::install_github("richelbilderbeek/beastier", ref = "develop")
        shell: Rscript {0}

      - name: Install BEAST2
        env:
          INSTALL_BEAST2_NS: ${{ matrix.install_beast2_ns }}
        run: if [[ "$INSTALL_BEAST2_NS" == true ]]; then Rscript -e 'beastier::install_beast2()'; fi

      - name: Install BEAST2 NS package
        env:
          INSTALL_BEAST2_NS: ${{ matrix.install_beast2_ns }}
        run: if [[ "$INSTALL_BEAST2_NS" == true ]]; then Rscript -e 'mauricer::install_beast2_pkg("NS")'; fi

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Lint
        run: lintr::expect_lint_free()
        shell: Rscript {0}

      - name: Good practice
        run: goodpractice::gp()
        shell: Rscript {0}

      - name: Report
        run: mcbette::mcbette_report()
        shell: Rscript {0}

